name: build vbmeta_tool

on:
  workflow_dispatch:
    inputs:
      create_release:
        description: 'Make a new release'
        type: boolean
        default: false
      tag:
        description: 'Release tag'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [arm64-v8a, armeabi-v7a]
    steps:
      - uses: actions/checkout@v5

      - name: Setup NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r28c
          add-to-path: false

      - name: Build with CMake
        run: |
          mkdir -p build && cd build
          cmake .. \
            -DCMAKE_TOOLCHAIN_FILE=${{ steps.setup-ndk.outputs.ndk-path }}/build/cmake/android.toolchain.cmake \
            -DANDROID_ABI=${{ matrix.arch }} \
            -DANDROID_NATIVE_API_LEVEL=26
          cmake --build .
          chmod +x vbmeta_tool
    
      - name: Install UPX
        run: sudo apt-get update && sudo apt-get install -y upx

      - name: Compress with UPX
        run: |
          upx --best --lzma build/vbmeta_tool -o vbmeta_tool

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.arch }}
          path: vbmeta_tool

  create_release:
    needs: build
    if: github.event.inputs.create_release && github.event.inputs.tag != ''
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v5
        with:
          path: artifacts

      - name: Create tar archive
        run: tar -czvf vbmeta_tool.tar.gz -C artifacts .

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: vbmeta_tool.tar.gz
          tag_name: ${{ github.event.inputs.tag }}
